from app.llm_provider import get_llm_client
from app.schemas.report import FundamentalAnalysis, SentimentAnalysis, CompetitorAnalysis, SectorAnalysis
from langchain_core.prompts import PromptTemplate

REPORT_PROMPT = """You are an expert financial writer. 
Synthesize the following agent outputs for {ticker} into a professional, structured markdown research report.

**Agent Data:**
Fundamental Data:
{fundamental_data}

Sentiment Data:
{sentiment_data}

Sector Data:
{sector_data}

Competitor Data:
{competitor_data}

Your markdown report MUST include:
1. An Executive Summary / Company Snapshot
2. Fundamental Assessment (summarizing KPIs, trends, and red flags)
3. Sentiment & Market Perception (including the Composite Sentiment Score and themes)
4. Sector & Peer Analysis (comparing the company to the identified competitors and sector trends)
5. A SWOT Analysis table (Strengths, Weaknesses, Opportunities, Threats)
6. Bull and Bear Cases
7. Investment Considerations

Constraints:
- Use professional financial language.
- Format beautifully with headers, bold text, and bullet points.
- Do NOT include any disclaimers; they will be appended programmatically.
"""

SEBI_DISCLAIMER = """
---
**Disclaimer (SEBI Compliance):**
*This report is generated by an Artificial Intelligence system for informational and educational purposes only. It does not constitute financial advice, a recommendation to buy or sell any security, or equity research as defined by the Securities and Exchange Board of India (SEBI). The data relies on automated scraping and LLM synthesis which may contain hallucinations or inaccuracies. Always consult a SEBI-registered investment advisor before making any financial decisions.*
"""

def generate_report(
    ticker: str,
    fundamentals: FundamentalAnalysis,
    sentiment: SentimentAnalysis,
    sector: SectorAnalysis,
    competitors: CompetitorAnalysis,
    provider: str = None
) -> str:
    """Generate the final markdown report using all gathered context."""
    
    prompt = PromptTemplate.from_template(REPORT_PROMPT)
    formatted_prompt = prompt.format(
        ticker=ticker,
        fundamental_data=fundamentals.model_dump_json(indent=2),
        sentiment_data=sentiment.model_dump_json(indent=2),
        sector_data=sector.model_dump_json(indent=2),
        competitor_data=competitors.model_dump_json(indent=2)
    )
    
    llm = get_llm_client(provider)
    
    try:
        response = llm.invoke([
            {"role": "system", "content": "You are an expert equity research analyst writing a professional report in markdown format."},
            {"role": "user", "content": formatted_prompt}
        ])
        
        report_content = response.content.strip()
        
        # Append hardcoded disclaimer
        return report_content + "\n\n" + SEBI_DISCLAIMER
        
    except Exception as e:
        return f"# Error Generating Report for {ticker}\n\nAn error occurred during report synthesis: {str(e)}"
